### ISSUE TITLE
Twitch API

### ISSUE THREAD

**Issue by webzi** [Decicus/twitch-log-bot#5]
Will you update this, so it works with the new twitch API?

Kraken/V5 will shutdown at 12th september.

**Comment by Decicus** [comment]
Kraken **V3** will be shutdown at September 12th, V5 will be fine (for the time being). This is clarified in the [Twitch API V3 Shutdown Timeline](https://discuss.dev.twitch.tv/t/twitch-api-v3-shutdown-timeline/21931)
> Starting on August 12, 2019, we will begin implementing scheduled outage windows of v3 endpoints over several weeks ending with a complete shutdown of v3 endpoints on September 12, 2019. If you do not take action to migrate your application to v5 of the API...

While I do plan on updating to the new Twitch API (aka Helix) at some point, I probably won't do so until the Helix API is fully complete and V5 has been scheduled for removal. This should work fine until then.
