### ISSUE TITLE
Add password access to web interface

### ISSUE THREAD

**Issue by ignaciocastro** [Decicus/twitch-log-bot#9]
Thanks for your script! It really works great and it's really easy to set up. Is there any way to add a password to the web interface? I'd like to have extra security in my logs.
Thank you!

**Comment by Decicus** [comment]
The software itself does not support any form of password, but if you use any form of reverse proxy in front of it ([NGINX](https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-as-a-web-server-and-reverse-proxy-for-apache-on-one-ubuntu-20-04-server) is pretty common and the one I use), then you could configure the reverse proxy to require [HTTP authentication](https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-nginx-on-ubuntu-14-04).
